name: Nx Workspace CI

on:
  pull_request:
    branches: main

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Lint affected projects
        run: npm run ci

      - name: Build affected projects
        run: npx nx affected -t build --base=origin/main --head=HEAD

      - name: Test affected projects
        run: npx nx affected -t test --base=origin/main --head=HEAD
